version: "3.1"

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      -  '/var/cache/postgres_data:/var/lib/postgresql/data:rw'